{% set version = "0.2.0" %}

package:
  name: pastel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pastel/pastel-{{ version }}.tar.gz
  sha256: 46155fc523bdd4efcd450bbcb3f2b94a6e3b25edc0eb493e081104ad09e1ca36

build:
  number: 0
  noarch: python
  script:
    # pastel cannot depend on itself via poetry
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    # - poetry >=1.0.0
  run:
    - python

test:
  imports:
    - pastel

about:
  home: https://github.com/sdispater/pastel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Bring colors to your terminal
  description: "Pastel is a simple library to help you colorize strings in your terminal."
  doc_url: https://pypi.org/project/pastel/
  dev_url: https://github.com/sdispater/pastel

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
