travis:
  secure:
    BINSTAR_TOKEN: Xg9jnrRHMvY3Rz5mOxY6x8JiaICXlM7rENtC2MQu0hKQ6Rj0Af6dhRy9K4j3TWatXCsVSgwG01iCKUs0Q8gRD0h93l3WxjqB48Ce/122bn+akidWiza4hEKSnGMx5gwnl+aG8mdmQI5FHHgV0A/CPKRHwxvk+NbKWSDwU5DrvYGY/8NJz2c/FbYqm+puy7qUHjNfXTq3pzFXQ6axFEJ4j5KqdjFBdZfG5baZ3jupvpN3aELguJXYUFwOcc2B4ce0L0BISV75RpUgWFkpcJNtfBQwZphoKKFOxDB3qCrzpjnL+SK+4jBXDk0Xf7rqoq/O8ckZqMuqAtDH+d5T7ukZ/YsfxqMvsk2E93FdLg3rBPx1QaWlDS3gLDWTQHafU0XxUfd3Tn8kjom2iw1QfAXFkZvJPNHMdgThZ7dra0WOTSD8baFd5iBh1dkRiO+BhbmrepqObC3jLoGiIdDDeg4OEhl8IqRKTpuQMm6D+Va7KbuHOmWYgnDFwK+rX0AgH7RlTCGY7nqKr0ZVpb7+75ftT+AuEhnSkQw5f1m3v326mS3nxPozL853Avj2wMV+Skl4I4KMvGwq1vqYQBO5WaOgZxHg9PdWqJh7Lyt+nQ9j9uVK5L2MggZuqtqs5F7AYcPYPkyLq+rO2p8IiQc1Jd5x/HCOdI56/NI8vwMY0KcDuLU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
