travis:
  secure:
    BINSTAR_TOKEN: kM2UteK8gaJBxr+yRqIRgN3kVC8oPMhSgHSRPbjHhGgboJCbvVOwiUmgGW6gdNUHXeRtltHeNWNaNPzPs/P6eLyHybyxnI8QklPMhwxvoW3QiIcMonTUvZkakkLEwj9fyIlTcUE7+mUJzl9e8ZuXLJH3EUGriytgerTMusBIWF7qB5Ns3so3UmoaP6fs5PHlAH1Gc70KaLCEqSwxDSghngvne3e9Q1gXqddQDvul02fatuttVR6/z2ikMW2JCsNtkvaS/0M7eWYb+miKmTKT8WkClv1kQublb7B5kGzrNcABiJNy7cd4CyBKMzVvr6mAgOwhyHJbsiWQeDiqvBNzaLXxkq9aPIYYD9nlHVAR/u59H5fPYQ8INLETiih1l6CsTKFJJIvRhg6v/pCF0DnLkJynhy6ZOV9Rv8RCt3WmRl1fx3IKHBonEGLXy3CFr5MutxAWQ4bLi82PIOS3fJigdrKEUrE45he39rhwxAiFtlThmgy9dV/lTuawB1bL2Be63L2OY+ZWxi2+6K+egWj7R8hqYvrEC+mXI52UMUXFKhIDFTNc4GMs4LTDLyk2QsIyVPFFB9aYhL0124Vam4N7EeV6nv/s5r9gb93UlY/Vhc1L29AbZbDIYEysZlrzJZE5M5l9Z2w3oxQst7jszGbve8/4WdcJR02m5pvBvBEwk7k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
